
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Aug 19 12:19:17 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BIGGEREQ = 25;
  public static final int LBRACKET = 40;
  public static final int CHAR = 51;
  public static final int CONST = 7;
  public static final int CONTINUE = 15;
  public static final int LESS = 26;
  public static final int FOR = 14;
  public static final int MINUS = 18;
  public static final int PERCENTEQUAL = 48;
  public static final int AND = 28;
  public static final int OR = 29;
  public static final int BOOL = 52;
  public static final int COMMA = 34;
  public static final int CLASS = 4;
  public static final int INC = 31;
  public static final int DIVEQUAL = 47;
  public static final int DIV = 20;
  public static final int NUM = 50;
  public static final int DIFFERENT = 23;
  public static final int PLUS = 17;
  public static final int LESSEQ = 27;
  public static final int ASSIGN = 30;
  public static final int IF = 8;
  public static final int DOT = 35;
  public static final int ABSTRACT = 5;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int RBRACKET = 41;
  public static final int EQUAL = 22;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 19;
  public static final int LCURLY = 36;
  public static final int PERCENT = 21;
  public static final int PLUSEQUAL = 44;
  public static final int IDENT = 49;
  public static final int BREAK = 3;
  public static final int BIGGER = 24;
  public static final int VOID = 43;
  public static final int RCURLY = 37;
  public static final int COLON = 42;
  public static final int FOREACH = 12;
  public static final int ELSE = 6;
  public static final int LSQUARE = 38;
  public static final int READ = 11;
  public static final int MINUSEQUAL = 45;
  public static final int RSQUARE = 39;
  public static final int EXTENDS = 16;
  public static final int DEC = 32;
  public static final int DOLAR = 53;
  public static final int MULEQUAL = 46;
  public static final int PRINT = 10;
  public static final int SEMICOMMA = 33;
}

